#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class SenseorValues
  include ::Thrift::Struct, ::Thrift::Struct_Union
  EXH2S = 1
  EXOXY2 = 2
  EXPH2 = 3
  EXTEMPL = 4
  EXAMPLECONDUCITIVITY2 = 5

  FIELDS = {
    EXH2S => {:type => ::Thrift::Types::DOUBLE, :name => 'exH2s'},
    EXOXY2 => {:type => ::Thrift::Types::DOUBLE, :name => 'exOxy2'},
    EXPH2 => {:type => ::Thrift::Types::DOUBLE, :name => 'exPH2'},
    EXTEMPL => {:type => ::Thrift::Types::DOUBLE, :name => 'exTempl'},
    EXAMPLECONDUCITIVITY2 => {:type => ::Thrift::Types::DOUBLE, :name => 'exampleConducitivity2'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class ReasonResult
  include ::Thrift::Struct, ::Thrift::Struct_Union
  REPORTH2S = 1
  REPORTGQOW = 2
  REPORTOIL = 3
  VERIFYDATA = 4

  FIELDS = {
    REPORTH2S => {:type => ::Thrift::Types::BOOL, :name => 'reportH2S'},
    REPORTGQOW => {:type => ::Thrift::Types::BOOL, :name => 'reportGQOW'},
    REPORTOIL => {:type => ::Thrift::Types::BOOL, :name => 'reportOil'},
    VERIFYDATA => {:type => ::Thrift::Types::BOOL, :name => 'verifyData'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

