#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'interface_types'

module OntologyService
  class Client
    include ::Thrift::Client

    def getInitValues()
      send_getInitValues()
      return recv_getInitValues()
    end

    def send_getInitValues()
      send_message('getInitValues', GetInitValues_args)
    end

    def recv_getInitValues()
      result = receive_message(GetInitValues_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'getInitValues failed: unknown result')
    end

    def perfomReason(sensors)
      send_perfomReason(sensors)
      return recv_perfomReason()
    end

    def send_perfomReason(sensors)
      send_message('perfomReason', PerfomReason_args, :sensors => sensors)
    end

    def recv_perfomReason()
      result = receive_message(PerfomReason_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'perfomReason failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_getInitValues(seqid, iprot, oprot)
      args = read_args(iprot, GetInitValues_args)
      result = GetInitValues_result.new()
      result.success = @handler.getInitValues()
      write_result(result, oprot, 'getInitValues', seqid)
    end

    def process_perfomReason(seqid, iprot, oprot)
      args = read_args(iprot, PerfomReason_args)
      result = PerfomReason_result.new()
      result.success = @handler.perfomReason(args.sensors)
      write_result(result, oprot, 'perfomReason', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class GetInitValues_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class GetInitValues_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::SenseorValues}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class PerfomReason_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SENSORS = 1

    FIELDS = {
      SENSORS => {:type => ::Thrift::Types::STRUCT, :name => 'sensors', :class => ::SenseorValues}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class PerfomReason_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::ReasonResult}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

